[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["../invariant_lab/lib"]
remappings = ["forge-std/=../invariant_lab/lib/forge-std/src/"]
solc_version = "0.8.20"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200
via_ir = true
