"""Evaluate ChainEDR's bytecode-level AA7702 detector on runtime bytecode
fetched from mainnet.

Pairs with `benchmarks/external_v1/bytecode/`. Each sample's hex string was
returned by `eth_getCode` against the address recorded in labels.json — none
of the bytes were authored by the ChainEDR maintainers.

The scoring mirrors `scripts/external_evaluator.py`: for each sample,
compare observed fires to expected fires, then summarise
`precision_on_aa7702_fires` (share of fires whose verdict is TP or ARCH).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent


def _load_detector():
    # Strip any previously-cached chainedr / bytecode_oracle modules so the
    # detector loaded here is the in-tree one, not one shadowed by a parallel
    # worktree on sys.path.
    for k in list(sys.modules):
        if k.startswith("chainedr") or k == "bytecode_oracle":
            del sys.modules[k]
    sys.path.insert(0, str(REPO / "src"))
    import bytecode_oracle  # type: ignore[import-not-found]

    return bytecode_oracle


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--corpus",
        default=str(REPO / "benchmarks" / "external_v1" / "bytecode"),
    )
    args = parser.parse_args()

    bytecode_oracle = _load_detector()

    corpus = Path(args.corpus)
    labels_path = corpus / "labels.json"
    labels = json.loads(labels_path.read_text(encoding="utf-8"))

    rows = []
    fires_total = 0
    fires_useful = 0
    correct_count = 0
    drift_count = 0
    regress_count = 0
    for sample in labels["samples"]:
        hex_path = corpus / sample["path"]
        if not hex_path.exists():
            print(f"missing: {hex_path}", file=sys.stderr)
            continue
        raw = hex_path.read_text(encoding="utf-8").strip()
        if raw.startswith("0x"):
            raw = raw[2:]
        findings = bytecode_oracle.detect_bytecode_aa7702(raw)
        observed = sorted({f.rule_id for f in findings})
        expected = sorted(sample.get("fires") or [])
        verdict = sample.get("verdict", "?")

        if observed == expected:
            outcome = "CORRECT"
            correct_count += 1
        else:
            outcome = "DRIFT"
            drift_count += 1

        if verdict == "FP":
            regress_count += 1
            outcome = "REGRESS"

        for _ in observed:
            fires_total += 1
            if verdict in {"TP", "ARCH"}:
                fires_useful += 1

        rows.append({
            "id": sample["id"],
            "address": sample["address"],
            "expected_fires": expected,
            "observed_fires": observed,
            "verdict": verdict,
            "outcome": outcome,
            "rationale": sample.get("rationale", ""),
        })

    precision = (
        fires_useful / fires_total if fires_total > 0 else 1.0
    )

    summary = {
        "corpus": labels["name"],
        "version": labels["version"],
        "samples": len(labels["samples"]),
        "correct": correct_count,
        "drift": drift_count,
        "regress": regress_count,
        "aa_fires_total": fires_total,
        "aa_fires_useful": fires_useful,
        "precision_on_aa7702_fires": round(precision, 4),
    }

    out_md = REPO / "docs" / "EXTERNAL_BYTECODE_BENCHMARK.md"
    out_json = REPO / "docs" / "external_bytecode_benchmark.json"
    out_json.write_text(
        json.dumps({"summary": summary, "rows": rows}, indent=2),
        encoding="utf-8",
    )
    out_md.write_text(_render_md(summary, rows), encoding="utf-8")
    print(json.dumps(summary, indent=2))
    print(f"\nWrote {out_md.relative_to(REPO)}")
    print(f"Wrote {out_json.relative_to(REPO)}")
    return 0


def _render_md(summary: dict, rows: list[dict]) -> str:
    lines = [
        "# External Bytecode Benchmark Results",
        "",
        "Auto-generated by `scripts/external_bytecode_evaluator.py` against",
        "`benchmarks/external_v1/bytecode/`. Every sample is runtime bytecode",
        "fetched live from mainnet via `eth_getCode` — none of the bytes",
        "were authored by the ChainEDR maintainers.",
        "",
        "## Headline",
        "",
        f"- Corpus: **{summary['corpus']} v{summary['version']}**",
        f"- Samples: **{summary['samples']}**",
        f"- CORRECT / DRIFT / REGRESS: "
        f"**{summary['correct']} / {summary['drift']} / "
        f"{summary['regress']}**",
        f"- Total AA-\\* opcode fires: **{summary['aa_fires_total']}**",
        f"- Useful fires (TP + ARCH): **{summary['aa_fires_useful']}**",
        f"- **Precision on AA fires: "
        f"{summary['precision_on_aa7702_fires'] * 100:.1f}%**",
        "",
        "## Per-sample",
        "",
        "| Sample | Address | Expected | Observed | Verdict | Outcome |",
        "|---|---|---|---|---|---|",
    ]
    for r in rows:
        short_addr = r["address"][:10] + "..." + r["address"][-4:]
        lines.append(
            f"| `{r['id']}` | `{short_addr}` | "
            f"{', '.join(r['expected_fires']) or '—'} | "
            f"{', '.join(r['observed_fires']) or '—'} | "
            f"**{r['verdict']}** | "
            f"**{r['outcome']}** |"
        )
    lines.append("")
    lines.append("## Rationale per sample")
    lines.append("")
    for r in rows:
        lines.append(
            f"- `{r['id']}` ({r['verdict']} / {r['outcome']}): "
            f"{r['rationale']}"
        )
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    raise SystemExit(main())
